version: '3.1'
services:
  app:
    container_name: developer-test-task
    image: developer-test-task
    build: ./
    ports:
      - "8189:8189"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=developer-test-task